//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Course { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Address { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Email { get; set; }
    }
}
